In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')


[2017-07-09 17:56:52,704] Making new env: FrozenLake-v0


In [4]:
print env.observation_space

Discrete(16)


In [5]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
print Q.shape
print env.reset()

(16, 4)
0


In [35]:
# Set learning parameters
lr = .8
y = .95
num_episodes = 100
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    print "----------------------------"
    print "s: ",s
    print "----------------------------"
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        c=Q[s,:]
        print "c: ",c
        b= c + np.random.randn(1,env.action_space.n)*(1./(i+1))
        print "b: ",b
        a = np.argmax(b)
        print "a: ",a
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        print env.step(a)
        print "Q[",s,",:] ",Q[s,:]
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        print "Q[",s,",",a,"] ",Q[s,a]
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

----------------------------
s:  0
----------------------------
c:  [ 0.  0.  0.  0.]
b:  [[-0.35026058  0.03438752 -0.9676978   0.30518647]]
a:  3
(1, 0.0, False, {'prob': 0.3333333333333333})
Q[ 0 ,:]  [ 0.  0.  0.  0.]
Q[ 0 , 3 ]  0.0
c:  [ 0.  0.  0.  0.]
b:  [[-0.09284698 -1.09292527  0.13101886 -0.7601891 ]]
a:  2
(1, 0.0, False, {'prob': 0.3333333333333333})
Q[ 0 ,:]  [ 0.  0.  0.  0.]
Q[ 0 , 2 ]  0.0
c:  [ 0.  0.  0.  0.]
b:  [[ 1.76143623  1.20505538  0.66198641  0.26582895]]
a:  0
(1, 0.0, False, {'prob': 0.3333333333333333})
Q[ 1 ,:]  [ 0.  0.  0.  0.]
Q[ 1 , 0 ]  0.0
c:  [ 0.  0.  0.  0.]
b:  [[ 0.17120122 -0.05599292  0.79202033  0.70443807]]
a:  2
(2, 0.0, False, {'prob': 0.3333333333333333})
Q[ 1 ,:]  [ 0.  0.  0.  0.]
Q[ 1 , 2 ]  0.0
c:  [ 0.  0.  0.  0.]
b:  [[-0.69060921  2.1523755  -0.02262418  0.1103923 ]]
a:  1
(7, 0.0, True, {'prob': 0.3333333333333333})
Q[ 2 ,:]  [ 0.  0.  0.  0.]
Q[ 2 , 1 ]  0.0
c:  [ 0.  0.  0.  0.]
b:  [[ 1.97505629  0.00779768  0.79124025 -0.

In [7]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.0


In [36]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  6.99867632e-03   1.54941427e-03   2.75070523e-03   8.18252487e-03]
 [  1.63456540e-03   8.04166946e-04   9.44339118e-04   1.42393454e-03]
 [  2.61427162e-04   7.46044059e-03   6.92375393e-03   5.53862803e-03]
 [  5.28896577e-03   7.55627985e-05   9.03347532e-04   3.77813992e-04]
 [  1.45784559e-04   0.00000000e+00   1.53991794e-03   6.23939747e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   4.78791454e-03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.16675325e-03   7.67233596e-04   5.00695429e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.30335590e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.23136000e-01   0.00000000e+00   0

In [32]:
env.action_space.sample()

2